### ISSUE TITLE
Implement Peer and Peerstore

### ISSUE THREAD

**Issue by zixuanzh** [zixuanzh/py-libp2p#10]
References:

https://github.com/libp2p/go-libp2p-peerstore
https://github.com/libp2p/go-libp2p-peer

**Comment by zixuanzh** [comment]
please also add docstring to`peer.py` and `peerstore.py` @stuckinaboot

**Comment by zixuanzh** [comment]
can you also rename peerdata to peerinfo to be consistent with the interfaces? @stuckinaboot 

reference: https://github.com/libp2p/interface-connection

**Comment by robzajac** [comment]
Please also rewrite error handling to use Python exceptions instead of returning errors from functions. We can rewrite tests accordingly (#21) after.

**Comment by stuckinaboot** [comment]
> can you also rename peerdata to peerinfo to be consistent with the interfaces? @stuckinaboot
> 
> reference: https://github.com/libp2p/interface-connection

PeerData encompasses all data about a peer. PeerInfo is a small subset of that data. They are two different things. @zixuanzh

**Comment by zixuanzh** [comment]
see #26
