### ISSUE TITLE
fix function info_from_p2p_addr in peerinfo.py

### ISSUE THREAD

**Issue by tranlyvu** [zixuanzh/py-libp2p#102]
This function used multiaddr.protocols.P_IPFS which is deprecated and can no longer be found from [multiaddr source code](https://github.com/multiformats/py-multiaddr/blob/master/multiaddr/protocols.py)

**Comment by robzajac** [comment]
https://github.com/zixuanzh/py-libp2p/blob/master/libp2p/peer/peerinfo.py#L15

Fixed in #99.
