### ISSUE TITLE
Overall structure.

### ISSUE THREAD

**Issue by magniff** [zixuanzh/py-libp2p#104]
Usually python libs are structured in following manner:
```
├── examples
├── LICENSE
├── README.md
├── **setup.py**
├── tests
├── **libp2p**
```
Note, that `requirements.txt` is usually discouraged for libraries, it is more like application level dependency definition facility. Also, all the relevant contents are packed to the single folder, which name goes to `packages=...` arg for `setuptools.setup` function.
Proposed structure is simply cleaner to follow and use, for instance once you got your `python setup.py develop` you get
- "Installed" version of your lib, so no need of writing weird things like:
```bash
$ python examples/chat/chat.py 
Traceback (most recent call last):
  File "examples/chat/chat.py", line 8, in <module>
    from libp2p.libp2p import *
ImportError: No module named 'libp2p'
``` 
- Auto update of code while developing.
- You actually need `setup.py` in order to pack your code as a PyPI package.

I can help on that, if needed.

**Comment by robzajac** [comment]
Thanks @magniff, this makes sense to us. Are you planning to open a PR or should we do so?

**Comment by magniff** [comment]
@robzajac I am planning to open a MR this evening.

**Comment by magniff** [comment]
See https://github.com/zixuanzh/py-libp2p/pull/105

**Comment by magniff** [comment]
Awesome, looking forward for #107
