### ISSUE TITLE
QUESTION: Changing to python-cryptography for encryption ?

### ISSUE THREAD

**Issue by Jorropo** [zixuanzh/py-libp2p#118]
All is explained in #116.
I would have your though, must we stay with the slow Crypto are can we switch to Cryptography ?

**Comment by alexh** [comment]
Hey @Jorropo we appreciate your enthusiasm for this project. Introducing new dependencies requires research and vetting. We see #116 and are contemplating. Please direct further discussion on this to the comments on #116

**Comment by Jorropo** [comment]
@alexh ok sorry, I created a duplicate here because I was thinking that discussion about tech used where not in the scope of accepted discussion in PR :)
