### ISSUE TITLE
Improved peer ID construction and usage

### ISSUE THREAD

**Issue by robzajac** [zixuanzh/py-libp2p#65]
As mentioned in #64, the py-libp2p notion of a peer ID should mirror the Go libp2p notion by taking the SHA256 hash of the public key generated for the host. More generally, py-libp2p should have a cleaner abstraction for dealing with peer IDs and they should be used more consistently in the library (instead of using simplistic peer IDs like [certain parts of the code](https://github.com/zixuanzh/py-libp2p/blob/master/tests/libp2p/test_libp2p.py#L25) currently use).

**Comment by zaibon** [comment]
I have already some part of it, see https://github.com/zixuanzh/py-libp2p/compare/master...zaibon:master

This is the basic code to create a peer id from the public key. I simply ported the Go code to python.

**Comment by zaibon** [comment]
Ok I have a first version that uses proper peer id and multiaddr addresses: https://github.com/zaibon/py-libp2p/tree/multiaddr

Let me know if any of this is interesting and goes to the direction you were planning for py-lip2p and I'll open some PR.

**Comment by zixuanzh** [comment]
Yes, we talked about adapting [sbuss/py-multiaddr](https://github.com/sbuss/py-multiaddr) earlier and using it in py-libp2p as per discussion https://github.com/multiformats/multiaddr/issues/7#issuecomment-439380831.

@raulk what's our plan with moving py-multiaddr into the libp2p org? @zaibon did some great work here and I think we can merge it into py-multiaddr. py-libp2p can be adapted accordingly too.

**Comment by raulk** [comment]
@zixuanzh

@sbuss has kindly agreed to transfer his repo to the libp2p org so it can evolve there. See Twitter thread: https://twitter.com/raulvk/status/1064664050351652865?s=21

I’ll prepare the repo by sending a PR upstream, and once merged we can transfer it over and give you access.

**Comment by robzajac** [comment]
Yes, thanks for following up.
