### ISSUE TITLE
Assigning port numbers in tests to avoid sharing ports

### ISSUE THREAD

**Issue by robzajac** [zixuanzh/py-libp2p#89]
As mentioned in #82, until we move to mocking network communication, we should assign ports to hosts in our test cases in a more canonical way which avoids: 

1) different tests trying to communicate on the same port
2) assigning port numbers [ad-hoc](https://github.com/zixuanzh/py-libp2p/blob/master/tests/protocol_muxer/test_protocol_muxer.py#L58)

One way to do this is to have tests share a _next_port function which gives a monotonically increasing port number.

**Comment by zaibon** [comment]
In go, when you used 0 as port number when listening on a socket, a random port is automatically chosen, I think `asyncio.start_server` behave the same.
So in the test we could just use 0 as port number. This would avoid any need of manually managing ports at all.
